version: '3.9'

services:

  # backend:
  #   depends_on:
  #     - db
  #     - rabbitmq
  #   build:
  #     context: ./src/
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./src/.env
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./src/:/app
  #   command: sh -c "python /app/app.py"


  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/var/lib/mongodb/data/
    networks:
      - mongo_network

  rabbitmq:
    image: rabbitmq:3.11-management
    restart: always
    ports:
      - 5672:5672

volumes:
  mongo_data:

networks:
  mongo_network:
