version: '3.9'

services:
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234

    volumes:
      - mongo_data:/var/lib/mongodb/data/
    
    ports:
      - 5433:5432

volumes:
  mongo_data:
