version: "3.9"

services:
  
  backend:
    depends_on:
      - db
    build:
      context: ./src/
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    expose:
      - 8000
    # ports:
    #   - 8000:8000
    volumes:
      - ./src/:/app
      - static_files:/app/staticfiles
    command: sh -c "sh /app/migrate.sh && sh /app/entrypoint.sh && sh /app/collectstatic.sh"

  db:
    image: postgres:15.1
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
    ports:
      - 5432:5432

  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/home/app/staticfiles
    depends_on:
      - backend

volumes:
  postgres_data:
  static_files:
